Repository AY2223S2-CS2103T-W15-3/tp, pull requests merged in 2023-03, with the labels that each got.

#29 Update README.md
  README.md
Labels: documentation

#48 Add assign command
  docs/UserGuide.md
  src/main/java/seedu/address/commons/core/index/Index.java
  src/main/java/seedu/address/logic/commands/AssignTaskCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/AssignTaskCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/person/UniquePersonList.java
  src/main/java/seedu/address/model/task/Task.java
  src/main/java/seedu/address/model/task/UniqueTaskList.java
  src/main/java/seedu/address/ui/Ui.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/AssignTaskCommandTest.java
  src/test/java/seedu/address/logic/commands/DeadlineCommandTest.java
  src/test/java/seedu/address/testutil/TypicalIndexes.java
Labels: enhancement

#62 Fix UI elements
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/AssignTaskCommand.java
  src/main/java/seedu/address/logic/commands/ViewCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/UniquePersonList.java
  src/main/java/seedu/address/model/role/Role.java
  src/main/java/seedu/address/model/task/DeadlineTask.java
  src/main/java/seedu/address/model/task/Task.java
  src/main/java/seedu/address/model/task/UniqueTaskList.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/TaskCard.java
  src/main/java/seedu/address/ui/TaskListPanel.java
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/TaskListCard.fxml
  src/main/resources/view/TaskListPanel.fxml
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/AssignTaskCommandTest.java
  src/test/java/seedu/address/logic/commands/DeadlineCommandTest.java
Labels: enhancement

#79 Update DG
  build.gradle
  docs/DeveloperGuide.md
Labels: documentation

#78 Chore: Update developer guide
  docs/DeveloperGuide.md
  docs/images/DeleteCommandUML.png
  src/main/resources/UmlDiagrams/DeleteCommand.puml
Labels: documentation

#80 Update DG
  docs/DeveloperGuide.md
Labels: documentation

#88 UI update
  src/main/java/seedu/address/logic/commands/CommentCommand.java
  src/main/java/seedu/address/logic/commands/MarkCommand.java
  src/main/java/seedu/address/logic/commands/UnmarkCommand.java
  src/main/java/seedu/address/model/task/Comment.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/TaskCard.java
  src/main/resources/view/CommandBox.fxml
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/PersonListCard.fxml
  src/main/resources/view/PersonListPanel.fxml
  src/main/resources/view/ResultDisplay.fxml
  src/main/resources/view/StatusBarFooter.fxml
  src/main/resources/view/TaskListCard.fxml
  src/main/resources/view/TaskListPanel.fxml
Labels: UI

#91 Feat: Add edittask command
  docs/UserGuide.md
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/EditTaskCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditTaskCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/TaskBook.java
  src/main/java/seedu/address/model/TaskBookModel.java
  src/main/java/seedu/address/model/TaskBookModelManager.java
  src/main/java/seedu/address/model/task/Task.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/DeadlineCommandTest.java
  src/test/java/seedu/address/logic/commands/EventCommandTest.java
  src/test/java/seedu/address/logic/commands/ToDoCommandTest.java
Labels: enhancement, feature

#92 Fix UI
  src/main/java/seedu/address/logic/commands/AssignTaskCommand.java
  src/main/java/seedu/address/logic/commands/CommentCommand.java
  src/main/java/seedu/address/logic/commands/MarkCommand.java
  src/main/java/seedu/address/logic/commands/UnmarkCommand.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/TaskBook.java
  src/main/java/seedu/address/model/TaskBookModel.java
  src/main/java/seedu/address/model/TaskBookModelManager.java
  src/main/java/seedu/address/model/task/Task.java
  src/main/java/seedu/address/model/task/UniqueTaskList.java
  src/main/java/seedu/address/ui/HelpWindow.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/TaskCard.java
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/TaskListCard.fxml
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/DeadlineCommandTest.java
  src/test/java/seedu/address/logic/commands/EventCommandTest.java
  src/test/java/seedu/address/logic/commands/MarkCommandTest.java
  src/test/java/seedu/address/logic/commands/ToDoCommandTest.java
  src/test/java/seedu/address/logic/commands/UnmarkCommandTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
Labels: enhancement, UI

#95 Add Task Status
  src/main/java/seedu/address/model/task/DeadlineTask.java
  src/main/java/seedu/address/model/task/EventTask.java
  src/main/java/seedu/address/model/task/Task.java
  src/main/java/seedu/address/ui/TaskCard.java
  src/main/java/seedu/address/ui/TaskListPanel.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/TaskListCard.fxml
Labels: enhancement, UI

#105 Add dark mode
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/resources/view/MainWindow.fxml
Labels: UI
